bootloader:
  screen_width: 800
  screen_height: 600
  screen_bpp: 8

kernel:
  TASK_QUEUE_SIZE: 8
  SERIAL_PORT_COUNT: 1
  SERIAL_RECV_BUF: 8
  SERIAL_SEND_BUF: 32

resources:
  subdirs: [dro]
  palette: ../vga.bmp